### ISSUE TITLE
add optional dedicated `EVALUATOR` for discovery.

### ISSUE THREAD

**Issue by nrdxp** [divnix/std-action#10]
When available consumer jobs could use the json to simply `nix copy --from $EVALUATOR $target` to avoid a long wait in the event of a heavy evaluation (due to the github cache, which can take a while to decompress with evals of several GB), but this scheme would allow us to copy only the derivations relevant to the given target.

**Comment by blaggacao** [comment]
superseded by abstract interface implementations via #13 & #14.

#13 should implement the stub for this.
