### ISSUE TITLE
Filter out concluded targets

### ISSUE THREAD

**Issue by blaggacao** [divnix/std-action#2]
### Concluded Targets

- Targets that have a cache hit
- Simplifying Assumption: not only has the target been built, but also its action "concluded"

Hence, filter out concluded targets at the discovery phase in order to reduce:
- total duration
- billable time

**Comment by nrdxp** [comment]
so you want to move the cache checking into discovery? Makes sense

**Comment by blaggacao** [comment]
We probably should do that, yep. If the simplifying assumption results beeing all too simplifying, we can thing of a more clever logic, still.

**Comment by nrdxp** [comment]
Okay so here is basically how I am thinking:
* Ditch parsing the `--dry-run`, even though it gives us exactly the information we need, its too _ad hoc_ leaving open the possibility of uncached build deps, and also, it would be inefficient to do sequentially in discovery.
* Instead use `nix-store --query --requisites --include-outputs` and run the result against `nix-path --store`, if any of the paths in the build closure are uncached it will exit with an error, which we can capture as a simple boolean.
* longer term, we want to fix `nix path-info` to make this more efficient: https://github.com/NixOS/nix/issues/3946#issuecomment-1344612074

**Comment by nrdxp** [comment]
> Looks like this question therefore goes away.

No, I think it is actually worth it after all. The action takes longer when the /nix/store its installing into is longer, obviously if we are restoring a large /nix/store from the GH cache we are gonna be waiting for basically nothing. x-ref: https://github.com/divnix/std-action/issues/11#issuecomment-1346700267

**Comment by blaggacao** [comment]
> Does it really waste anything if the job is a complete no-op? Just starts logs and stops?

Yes 48 USD-Cents / hour on the leanest instance.

**Comment by nrdxp** [comment]
The biggest blocker to doing this is just an efficient way to check the caches:
https://github.com/NixOS/nix/issues/3946#issuecomment-1350047314

We could just do either `nix path-info` or `nix-build --dry-run` in sequence, but I don't want to make discovery any more expensive than it absolutely has to be.

**Comment by blaggacao** [comment]
We could place a `./filter` action in between that further optimizes on the assumptions of this issue.

**Comment by blaggacao** [comment]
Superseded by #28, which aims to be more explicit and reliable and doesn't "conclude" remote state but actually "checks" it.
