### ISSUE TITLE
hermetic evaluation

### ISSUE THREAD

**Issue by nrdxp** [divnix/std-action#23]
Calling `nix` directly on flake uris in "actions" has a more important consequence than merely risking inefficiencies. It breaks the guarantee that the artifacts we are acting upon in CI all come from a single source. It is imperative, therefore, to keep evaluation encapsulated to a single operation.

This is part of the reason why I've gone to some pains to give myself something to capture a Nix shell, produced by `nix develop`, at evaluation time: https://github.com/NixOS/nix/issues/7468#issuecomment-1356408361 https://github.com/NixOS/nixpkgs/pull/206915

I have convered _almost_ all of the actions so far in this upstream PR: https://github.com/divnix/std/pull/206

**Comment by blaggacao** [comment]
> breaks the guarantee

Yes, we delegate that guarantee to the CI system, which still implements it, but we loosen the control loop.

**Comment by blaggacao** [comment]
As for the devshell use case, we now have: https://github.com/NixOS/nixpkgs/pull/206728

As for the general Standard Action use case, we probably should open an issue in `std`.

**Comment by nrdxp** [comment]
I don't like the idea of stripping out `nix develop` from the core of nix and instead relying on nixpkgs. Also, unless there is some way to avoid it, this would create a lot of different possible end results whereas now, everything gets reduced to the same interface.

In any case, I can't use that atm, as a "close approxmimation" is not enough to make mamba happy. I already begun to create a compatibility derivation though at it works to capture the devshell as a build dep, and also to enter it before the run. I left an additional comment in the upstream issue as well.

**Comment by blaggacao** [comment]
To further the reader's context:

> begun to create a compatibility derivation

https://github.com/divnix/std/pull/206/commits/c54501e16825b9f5ba35761af6694f8b89b5fb51
