### ISSUE TITLE
Avoid nix install action

### ISSUE THREAD

**Issue by blaggacao** [divnix/std-action#24]
There may be ways to avoid the nix install action and rather directly restore what would end up being a single user install from the cache enriched with same installation & configuration routine that comes shipped with the `std-action`.

A variant would be to contribute to upstream in order to achieve these properties.

**Comment by blaggacao** [comment]
Here you have it:

https://github.com/nixbuild/nix-quick-install-action

**Comment by rickynils** [comment]
@blaggacao Do you think cache-restore can be used when other repos are using `nix-quick-install-action`? They won't have access to the cache, will they?

**Comment by blaggacao** [comment]
Yeah, actually let's close this issue.

The quick install has so stellar performance that this is hardly a problem for our main metric anymore.
