### ISSUE TITLE
feature: pre-run hook

### ISSUE THREAD

**Issue by nrdxp** [divnix/std-action#28]
It would be nice to have some sort of optional conditional check after the build phase to determine if we even need to run, something that has less context than the run phase itself so that it doesn't have to fetch the world to do the check.

Initial usecase would be to replace the _ad hoc_ skipping of the run action based on if the action is named "build", and also to allow for avoiding the derivation context entirely for OCI image uploads:
https://github.com/divnix/std/pull/206/commits/9a441e1efcfd349444125b7efb3b73b30b86cda6i

First phase could be in the job itself, but we could eventually move this entire check into discovery to save additional cycles.

**Comment by blaggacao** [comment]
This is an elegant alternative to #2. Closing there.

**Comment by nrdxp** [comment]
If we can get NixOS/nix#7526 merged by the next release, we can do this the build check in discovery very cheaply.

**Comment by nrdxp** [comment]
This I have a solid implementation strategy. I think we should put this into discovery on the first pass after all, and do something like this:
* Include a new optional attribute in an actions definition `proviso`. This should be a short file using `builtins.toFile` with ideally no context, but if you need to pull in an external tool, say [nix-uncached](https://github.com/divnix/nix-uncached), you can do that here, but we need to keep the context as minimal as possible since that would induce IFD. This file also then gets a reference in the CI JSON.

* Include another optional attribute `meta` in the type def that can include any context-free information that might be useful to the proviso snippet, say an OCI image's full name

* After the intial eval in discovery iterate over the list of actions and run any "proviso" that exist. These short scripts will take a reference to their actions JSON, so they can read the meta, and if it is determined that the action does not need to run, they should exit non-zero. Any such actions will then be removed from the list, before we build the `block->action` object which is ultimately sent as the final output.

**Comment by blaggacao** [comment]
A couple of quick questions:

- Can you exemplify the various target use cases for `meta`? (And maybe explain why it can't be avoided?)

- By which mechanism does `proviso` induce IFD?

**Comment by nrdxp** [comment]
> A couple of quick questions:
> 
> * Can you exemplify the various target use cases for `meta`? (And maybe explain why it can't be avoided?)

I suppose it is not strictly necessary, just a nice to have so that one can quickly spot context in the `proviso` by whether or not it has any interpolation.

> * By which mechanism does `proviso` induce IFD?

Normally we want this text to be entirely context free, but in some situations a particular tool may be absolutely necessary and unavoidable, so long as it is a reasonably small tool, we can use IFD here to reference its output. For example:
```nix
{
  # ...
  proviso = ''
    # since we are referencing the outpath here, it will have to be built, thus IFD
    ${pkgs.someTool}/bin/tool # ....
  '';
}
```

**Comment by blaggacao** [comment]
Got ya! Thx!

If `meta` isn't strictly necessary, then let's avoid expanding the api just for a nice to have, unless its value becomes sufficiently evident.
